- contrib/coredns/policy/policy.go
- contrib/coredns/policy/setup.go
- pdpserver/config.go
- pdpserver/control.go
- pdpserver/queue.go
- pdpserver/server.go
- pdpserver/service.go
- pep/client.go
Adds the basic CoreDNS policy middleware.
go fmt some of the code
Allow PEP users to create their own Request and bypass marshaling. This was necessary because the CoreDNS attributes are dynamically defined.
> Coredns middleware

- contrib/coredns/policy/policy.go
The PEP unmarshaller expects the pdp tag for Permit field
to be capitalized.
> Fix PEP response

- contrib/coredns/policy/policy.go
import trace moved from "github.com/coredns/coredns/middleware/trace"
to "github.com/coredns/coredns/middleware/pkg/trace".
> Move trace package

- pep/client.go
- pep/client_test.go
Make Client an interface and add a TestClient implementation. This
allows unit tests to easily mock responses from the PDP in client
applications.
> Add TestClient

- contrib/coredns/policy/policy.go
- contrib/coredns/policy/setup.go
Added additional params for string conversion - stringOffset and stringSize.
Refactor EDNS attributes handling - set empty string ("") if we have attribute in config but don't have it in EDNS.
Example Corefile:
policy {
endpoint 127.0.0.1:5555
edns0 0xffee customer_id hex string 0 32 # make customer_id from first 16 bytes of client_id
edns0 0xffef policy_id
edns0 0xfff2 on_prem_host_id
}
> Improved handling EDNS attributes

- contrib/coredns/policy/policy.go
- contrib/coredns/policy/policy_test.go
- contrib/coredns/policy/setup.go
- contrib/coredns/policy/setup_test.go
ATM we have support for splitting any edns0 option to some separate attributes,
syntax:  edns0 [code]  [name] [dataType] [destType] [start] [end]
where [dataType] = hex, [start] is the start index in byte array, [end] is the end index in byte array + 1
Example:
edns0 0xffee customer_id hex string 0 16
edns0 0xffee client_id hex string 16 32
Attributes (data has size 32 bytes - getting from the option with 0xffee code):
customer_id = data[0:16] (first 16 bytes)
client_id = data[16:32] (last 16 bytes)
> Improved edns0 options handling

- pep/streaming_connection.go
Prevent disconnection from blocking retry channel reading
> Fixed deadlock on connection recovery

- contrib/coredns/policy/policy.go
- contrib/coredns/policy/policy_test.go
- contrib/coredns/policy/policytap.go
- contrib/coredns/policy/policytap_test.go
- Policy plugin doesn't depend on passed ResponseWriter anymore
- Policy plugin reset CQ and CR flags of dnstap plugin in beginning of
ServeDNS(). The flags are accessed via context
- Policy plugin now sends DNSTAP CR msg on REFUSED
- Removed ProxyWriter
> Refactor sending Dnstap msg from policy plugin

- pdp/content_test.go
- pdp/context.go
- pdp/policy.go
- pdp/storage.go
- pdp/storage_test.go
Change to make logs more informative:
Format from 
```
DEBU[0006]` Policy update                                 update=policy update: 93012340-27cc-47af-97a6-59cd654cf2cc - 7b9096d1-3ad1-4fbf-940d-193d4df780e1
commands:
- Add ("Default"/"query"/"DFPRNetworks"/"0000002e"/"Default")
- Add ("Default"/"query"/"DFPRNetworks"/"CIDRNetworks"/"0000002e"/"Default")
```
to
```
DEBU[0006] Policy update                                 update=policy update: 94db536a-f402-4ea9-a9cb-a3e3445bddf9 - 3664a605-97d3-427d-ac21-4acf8de56f96
commands:
- Add policy "Default" rules([Default News Blogs Tobacco Drugs]) to
path: ("Default"/"query"/"DFPRNetworks"/"00000001"/"Default")
- Add policy "Default" rules([Default News Blogs Tobacco Drugs]) to
path: …
```
> Fixed: No information in logs about category when its added to CF

- contrib/coredns/policy/setup.go
- Closing connection in OnRestart() was incorrect, since OnRestart()
is called before creation new instance of server, as opposed to
OnShutdown() handler which is called after creating the new instance
> Policy plugin: close connection to PDP in OnShutdown() handler

- pdpserver/config.go
- pdpserver/server/control.go
- pdpserver/server/memory.go
- pdpserver/server/server.go
`logger.WithFields(...).Fatal` exits using `os.Exit` which relies on system to close sockets. The change makes memory checker to call explicitly `Stop`.
> Made sure that PDP server shutdowns gracefully on high memory usage

- pdp/selector.go
- pdp/selector/local/init.go
- pdp/selector/local/local_selector.go
- pdp/selector/selector.go
- pdpserver/main.go
- pdpserver/server/server.go
Instead of registering a SelectorFunc, register object that implements a Selector interface which includes the following methods:
1) Enabled() - whether the selector is enabled
2) Initialize() - initialize the selector
3) SelectorFunc() - create the selector expression.
> Make selector interface

- contrib/coredns/policy/attrholder.go
- contrib/coredns/policy/attrholder_test.go
- contrib/coredns/policy/metrics.go
- contrib/coredns/policy/policy_test.go
- the action from the last validation wins. The appropriate policy
should be uploaded to PDP
- added comment to metrics
> plugin/policy: remove precedence of action log from the 1st validation

- pdp/content.go
In LocalContentStorageTransaction.Commit(), symbols was missing
when LocalContent is initialized.
> Missing symbols when initializing LocalContent

- pdp/flags_mapper_pca.go
- pdp/flags_mapper_pca_test.go
- pdp/flags_mapper_rca.go
- pdp/flags_mapper_rca_test.go
- pdp/mapper_pca.go
- pdp/mapper_pca_test.go
- pdp/mapper_rca.go
- pdp/mapper_rca_test.go
- pdp/marshal.go
- pdp/policy.go
- pdp/policy_set.go
- pdp/policy_set_test.go
- pdp/policy_test.go
- pdp/rule.go
- pdp/rule_test.go
I added MarshalJSON functions to the algorithms to easily marshal evaluables.
I'm under the assumption that recursive algorithms like Mapper wouldn't be very deep and therefore wouldn't have huge memory impact when marshalled to string
> Marshal Targets, Obligations, and Algorithms

- pdp/assignment.go
Package "testing" in production code of PDP library brings some unwanted options to every executable which uses the library. Result looks like:
```
$ pdpserver -help
Usage of pdpserver:
-auto-response
automatic respose buffer allocation
...
-test.bench regexp
run only benchmarks matching regexp
-test.benchmem
print memory allocations for benchmarks
-test.benchtime d
run each benchmark for duration d (default 1s)
...
```
The patch removes "testing" together with the options.
> Removed "testing" package from production code

- contrib/coredns/policy/attrholder.go
- contrib/coredns/policy/attrholder_test.go
recover PR #188 - plugin/policy: remove precedence of action log from the 1st validation
> recover PR#188 logic

- contrib/coredns/policy/dns.go
- contrib/coredns/policy/dns_test.go
- contrib/coredns/policy/policy.go
- the response should not be cached for log action, client should
send the query every time to make sure each query is logged
> policy plugin: reset ttl on log action

- contrib/coredns/policy/README.md
- contrib/coredns/policy/metrics.go
- contrib/coredns/policy/metrics_test.go
- enhanced sliced counter to store in single bucket the count of events
occured during time interval (quantum) more than one second
- autocalculate quantum based on expire value
- the default value for expire is 1 minute. Corefile config option
for 'expire' can be added later if requested
- added/updated unit tests
- updated README.md
> policy plugin: enhance metrics

- contrib/coredns/policy/dnstap_test.go
- contrib/coredns/policy/policy_test.go
- sendCRExtraMsg() doesn't spawn extra goroutine anymore, so there
is not need to use channels and goroutines in testIORoutine
- another reason is that dnstap related tests were failed sometimes
with WARNING: DATA RACE. The problem was in testIORoutine logic
> policy plugin: simplify dnstap tests

- contrib/coredns/policy/attrholder.go
- contrib/coredns/policy/client.go
- contrib/coredns/policy/client_test.go
- contrib/coredns/policy/dnstap.go
- contrib/coredns/policy/metrics.go
- contrib/coredns/policy/policy_test.go
- contrib/coredns/policy/setup.go
Updating to use CoreDNS logger result in the following changes in log messages generated by the CoreDNS policy plugin:
- The log message will now include the name of the plugin, which is included in the log message after the log level label. For example:
From:
`2018/08/13 09:29:07 [INFO] PDP request: [(string)type:query (domain)domain_name:www.yahoo.com. (string)dns_qtype:1 (address)source_ip:127.0.0.1]`
To:
`2018/08/13 09:31:32 [INFO] plugin/policy: PDP request: [(string)type:query (domain)domain_name:www.yahoo.com. (string)dns_qtype:1 (address)source_ip:127.0.0.1]`
- In order to NOT have to enable debug for CoreDNS and all its plugins, a number of DEBUG messages is now changed to INFO messages. This is to maintain existing behavior - currently, policy plugin DEBUG messages are …
> Updated CoreDNS plugin to use CoreDNS logger

- contrib/coredns/policy/client.go
- pep/client.go
- pep/streaming_client.go
- pep/streaming_client_test.go
- pep/unary_client.go
- pep/unary_client_test.go
The option allows a handler func to be specified which
is called when a decision request is served from the
decision cache.
Also updated contrib/coredns/policy to make use of this to
log decision request processed via decision cache.
> Added WithOnCacheHitHandler PEP Option

- contrib/coredns/policy/dns.go
- reset TTLs of AUTHORITY RRs as well, since NXDOMAIN responses
may not have records in ANSWER section
- removed check for OPT RR, since according to rfc6891 OPT RR should
appear in ADDITIONAL (Extra) section
> policy plugin: reset TTL on Log action to prevent caching

- contrib/coredns/policy/README.md
- contrib/coredns/policy/attrholder.go
- contrib/coredns/policy/attrholder_test.go
- contrib/coredns/policy/attributes.go
- contrib/coredns/policy/attributes_test.go
- contrib/coredns/policy/benchmark_test.go
- contrib/coredns/policy/client.go
- contrib/coredns/policy/client_test.go
- contrib/coredns/policy/config.go
- contrib/coredns/policy/config_test.go
- contrib/coredns/policy/debug.go
- contrib/coredns/policy/debug_test.go
- contrib/coredns/policy/dnstap.go
- contrib/coredns/policy/dnstap_test.go
- contrib/coredns/policy/edns0.go
- contrib/coredns/policy/metrics.go
- contrib/coredns/policy/policy.go
- contrib/coredns/policy/policy_test.go
- contrib/coredns/policy/pool.go
- added/modified attribute configuration in corefile. Affected options
are validation1, validation2, default_decision, metrics, dnstap. See
more details in README.md
- fallback to default decision in case if PDP validation failed.
- refactored debug query
- added integer "policy_action" attribute which contains explicit
action, i.e. now action is not deduced from existence and/or content of
other attributes. Removed attributes "refuse" and "drop"
- attribute "log" now defines the dnstap log level, i.e. the set of
attributes to be sent with dnstap message
> policy plugin: refactor attribute holder

- contrib/coredns/policy/client.go
- contrib/coredns/policy/debug.go
- contrib/coredns/policy/debug_test.go
- contrib/coredns/policy/policy.go
- contrib/coredns/policy/policy_test.go
- the length limit for TXT RR is 255 bytes, so dbgMessenger will
split single debug messsage into several shorter ones and
will guarantee that all messages are 255 chars or shorter
- beautified debug messages
- added restoreDebugMsg() method to restore original query data
> policy plugin: split long TXT records

- contrib/coredns/policy/README.md
- contrib/coredns/policy/attrholder.go
- contrib/coredns/policy/attrholder_test.go
- contrib/coredns/policy/dns.go
- contrib/coredns/policy/policy_test.go
- added info about predefined attributes
- choose the first A or AAAA record from DNS response for
validation since it is more likely that user will use
the first IP rather than the last one
- make "dns_qtype" attribute integer
> policy plugin: updated README

- contrib/coredns/policy/metrics.go
- cosmetic issue in metrics. Make VALUE_COUNT lowercase to have it
at the end of list of alphabetically sorted hexadecimal labels in
prometheus output
> policy plugin: make VALUE_COUNT lowercase

- README.md
- examples/12-lists/README.md
- examples/12-lists/lists.requests.yaml
- examples/12-lists/lists.yaml
- examples/README.md
- pepcli/README.md
- pepcli/config.go
- pepcli/requests/requests.go
- pepcli/test/config.go
- pepcli/test/test.go
Updates pepcli to handle list of strings and add some command line functionality:
- 	pepcli now can marshal list of string type and guess for list of strings
- 	pepcli takes in JSON or YAML filepaths or raw JSON for “-i” arg (fully backwards compatible)
- 	pepcli test package has flagparser option to sort list of strings returned in pdp response obligations
- 	examples package now has 12-lists, which covers a few brief pepcli use cases
New functionality can be tested with these generic commands (json not provided in PR):
- `pepcli -i '{"attributes”:{…},”requests”:[{…},…]}' test/perf` [raw json]
- `pepcli -i requests.json test/perf` [json filepath]
- `pepcli -i requests.yaml test -sort` [sort option]
> Pepcli update: list of strings and cl-args

- pdp/assignment.go
- pdp/assignment_test.go
- pdpserver/server/ctrl_storage.go
- pdpserver/server/ctrl_storage_test.go
I've noticed that the storage control/query endpoint has very few API documentation, so I'm adding the usage description to 404 error message. I've also exposed AttributeAssignment values when marshaling to JSON to get information on obligations.
> Add API description to ctrl_storage endpoint & Make AttributeAssignment Marshalable

- contrib/coredns/policy/dns.go
- contrib/coredns/policy/dns_test.go
- New format for redirect data to accommodate support for records of specific type
- New format like - "rrCode1=record1;rrCode2=record2;rrCode3=record3" , where rrCodeX = A/AAAA/CNAME/TXT"
Example - "A=127.0.0.1;AAAA=23ef:3546::8732;TXT=Ghguyw7g7yiug7;CNAME=google.com"
> Added new format for redirect string

- pdpserver/server/server.go
- pep/benchmark_test.go
Enables passing grpc interceptors to themis so we can leverage the grpc ecosystem middleware like grpc_prometheus and grpc_logrus.
> take standard gRPC ServerOption and expose gRPC Server

- pep/streaming_connection.go
- pep/streaming_connection_test.go
In case if streaming client cannot connect to PDP endpoint (for some reason)
the `func (c *streamConn) connect()` gets stuck in infinite loop. The proposed
fix is to break the loop when `func (c *streamConn) closeConn()` is called.
> pep client: break infinite loop in func (c *streamConn) connect()

- README.md
- pdp/content.go
- pdp/content_test.go
- pdp/jcon/errors.go
- pdp/jcon/errors.yaml
- pdp/jcon/item.go
- pdp/jcon/parser_test.go
- pdp/selector/local/local_test.go
- see updated README.md
- made getting content value recursive with aggregation on each level
if needed
- reused same code in `func (c *ContentItem) Get()` and
`func (c *ContentItem) GetByValues()` by introducing `keyProvider` handlers
- prevented collecting key descriptions in advance - they're needed only if
error happens
- updated/added unit tests
> add ability for content item to aggregate values

- pdp/content.go
- pdp/content_test.go
- if aggregation type is "append" (or "append unique") and the last key in the
list is unknown then the MissingValue error was unexpectedly returned even if
some data was already collected for the previous paths. Now it returns data
with no error in this case.
- fixed unit test logic to check actual error when no error expected
> fix aggregation type `append`
