contrib/coredns/policy/policy.go
pdpserver/config.go
pdpserver/logging.go
pdpserver/service.go

Add more logging levels

---

contrib/coredns/policy/policy.go

The issue occurs because `func (c *Client) Validate(ctx context.Context, in, out interface{}) error` doesn't take `Response` structure from "github.com/infobloxopen/policy-box/pdp-service" as "out" argument. It takes any structure and process it similar to json.Unmarshal. So I added following response structure:
```go
type Response struct {
Permit   bool   `pdp:"effect"`
Redirect net.IP `pdp:"redirect_to"`
}
```
Validate function uses "pdp" hints to translate protobuf response. Here it sets `Permit` to `true` only if response is "Permit" and `Redirect` to content of "redirect_to" obligation making validation that redirect_to is really IP address. If there is no "redirect_to" obligation in response field `Redirect` retains its previous value (in the case it's `nil`).

Fixed dissapearing obligation

---

pdpserver/config.go
pdpserver/main.go
pdpserver/server.go
pdpserver/service.go
pdpserver/trace.go

@johnbelamaric - I just realized that I haven't committed the PDP health check code from the last sprint. I have already rebased it to the latest master.

Add health check for PDP

---

Makefile
contrib/coredns/policy/policy.go
papcli/main.go
pdp/domain_tree.go
pdp/domain_tree_test.go
pdp/policy_set_test.go
pdp/policy_test.go
pdp/yast_policies_test.go
pdp/yast_selector_test.go
pdp/yast_target.go
pdpctrl-client/host.go
pep/marshal_test.go
pep/unmarshal_test.go
pepcli/client.go
pepcli/requests.go

Default make target now enforces gofmt with -s option.

Enforce gofmt

---

contrib/coredns/policy/policy.go
contrib/coredns/policy/policy_test.go

I have added changes as per the requirements I have understood, please confirm if changes are implemented correctly. Code is building, will confirm how to test it.

Response validation changes

---

Makefile
contrib/coredns/policy/policy_test.go

Added Unit tests for middleware response testing

Middle Response check Unit Tests

---

contrib/coredns/policy/policy_test.go

Middle response check rr6

---

pdp/attribute.go
pdp/attribute_test.go
pdp/mapper_rca.go
pdp/policy_set_test.go
pdp/selector.go
pdp/yast.go
pdp/yast_expression.go
pdp/yast_expression_test.go
pdp/yast_policies.go
pdp/yast_selector_test.go

This type if used instead of "Set of Strings" with selectors can reduce amount of required memory

Introduced List of Strings as selector and mapper compatible type

---

contrib/coredns/policy/policy.go

https://jira.inca.infoblox.com/browse/JANUS-8593

Fixed NXDOMAIN handling

---

README.md
examples/01-intro/README.md
examples/01-intro/all-permit.requests.yaml
examples/01-intro/all-permit.yaml
examples/01-intro/permit-x-test.requests.yaml
examples/01-intro/permit-x-test.yaml
examples/02-policy-set/README.md
examples/02-policy-set/policy-set.requests.yaml
examples/02-policy-set/policy-set.yaml
examples/03-policy/README.md
examples/03-policy/policy.requests.yaml
examples/03-policy/policy.yaml
examples/04-rule/README.md
examples/04-rule/rule.requests.yaml
examples/04-rule/rule.yaml
examples/05-target/README.md
examples/05-target/target.requests.yaml
examples/05-target/target.yaml
examples/06-values/README.md
examples/06-values/values.requests.yaml
examples/06-values/values.yaml
examples/07-selector/README.md
examples/07-selector/content.json
examples/07-selector/selector.requests.yaml
examples/07-selector/selector.yaml
examples/08-mapper/README.md
examples/08-mapper/content.json
examples/08-mapper/mapper.requests.yaml
examples/08-mapper/mapper.yaml
examples/README.md

Probably need to split this wall of text to several READMEs and put them to pdp, pdpserver and other directories. For now I prefer to merge it as is. And during work on development documentation and GoDocs make the split.

Added Themis user documentation

---

contrib/coredns/policy/policytap.go

- go routine doesn't increase performance (neither latency nor QPS)

remove go routine for sending dnstap message from policy plugin

---

examples/06-values/values.yaml
examples/07-selector/selector.yaml
pdp/ast/jast/parser_test.go
pdp/ast/jast/target.go
pdp/ast/yast/parser_test.go
pdp/ast/yast/target.go
pdp/selector/init.go
pdp/target.go

Also target doesn't to swap expression arguments anymore

Made selector not target compatible

---

README.md
examples/08-mapper/README.md
examples/08-mapper/mapper.requests.yaml
examples/08-mapper/mapper.yaml
pdp/ast/jast/algoritm.go
pdp/ast/jast/errors.go
pdp/ast/jast/errors.yaml
pdp/ast/jast/parser.go
pdp/ast/jast/parser_test.go
pdp/ast/yast/errors.go
pdp/ast/yast/errors.yaml
pdp/ast/yast/parser.go
pdp/ast/yast/parser_test.go
pdp/ast/yast/policies.go
pdp/attribute.go
pdp/attribute_test.go
pdp/context.go
pdp/mapper_pca.go
pdp/mapper_pca_test.go
pdp/mapper_rca.go
pdp/mapper_rca_test.go
pdp/policy.go
pdp/policy_set.go
pdp/policy_set_test.go
pdp/policy_test.go
pdp/rule.go
pdp/rule_test.go

This is preliminary PR. Will be updated in ongoing manner

Optional ordering for mapper algorithm

---

.travis.yml
contrib/coredns/policy/policy.go
contrib/coredns/policy/policy_test.go
pep/streaming_connection.go

Replacement for https://github.com/infobloxopen/themis/pull/121

Policy Plugin: delay closing connection to PDP

---

README.md
pdp/policy.go

Revert description logic in https://github.com/infobloxopen/themis/pull/123

Clean revert of previous description change

---

pdp/content.go
pdp/content_test.go

Added test for PR https://github.com/infobloxopen/themis/pull/189

Add tests for missing symbols

---

Makefile
README.md
contrib/coredns/policy/atributes.go
contrib/coredns/policy/attrholder.go
contrib/coredns/policy/attrholder_test.go
contrib/coredns/policy/benchmark_test.go
contrib/coredns/policy/metrics.go
contrib/coredns/policy/metrics_test.go
contrib/coredns/policy/policy.go
contrib/coredns/policy/policy_test.go
contrib/coredns/policy/setup.go
contrib/coredns/policy/setup_test.go
examples/11-funcs/README.md
examples/11-funcs/funcs.requests.yaml
examples/11-funcs/funcs.yaml
examples/README.md
pdp/ast/jast/algoritm.go
pdp/ast/jast/parser_test.go
pdp/ast/yast/parser_test.go
pdp/content.go
pdp/content_test.go
pdp/context.go
pdp/errors.go
pdp/errors.yaml
pdp/expr_concat.go
pdp/expr_concat_test.go
pdp/expr_list_of_strings_test.go
pdp/expr_try.go
pdp/expr_try_test.go
pdp/expression.go

Bringing up to date with master.

Coredns tight integration

---

contrib/coredns/policy/client.go

This fix CI breakage after merging #207

Update log message to use new logger

---

contrib/coredns/policy/attrholder_test.go
contrib/coredns/policy/attributes_test.go
contrib/coredns/policy/benchmark_test.go
contrib/coredns/policy/client_test.go
contrib/coredns/policy/debug_test.go
contrib/coredns/policy/dns_test.go
contrib/coredns/policy/dnstap_test.go
contrib/coredns/policy/policy_test.go
contrib/coredns/policy/testutil/attr_utils.go
contrib/coredns/policy/testutil/client_utils.go
contrib/coredns/policy/testutil/dns_utils.go
contrib/coredns/policy/testutil/dnstap_utils.go
contrib/coredns/policy/testutil/mock_plugin.go

- removed interdependencies between test files
- moved test utility code into separate package

policy plugin: refactor tests

---

contrib/coredns/policy/metrics.go

- registration logic was changed in coredns, see related PR
https://github.com/coredns/coredns/pull/2080

policy plugin: fix metrics registration

---

README.md
examples/07-selector/README.md
examples/07-selector/advanced.requests.yaml
examples/07-selector/advanced.yaml
examples/07-selector/content.json
pdp/ast/jast/parser_test.go
pdp/ast/jast/selector.go
pdp/ast/yast/parser_test.go
pdp/ast/yast/selector.go
pdp/selector.go
pdp/selector/local/local.go
pdp/selector/local/local_test.go
pdp/selector/pip/pip.go
pdp/selector/pip/pip_test.go

add 'default' and 'error' fields to selector

---

pdp/context.go
pdp/context_test.go

- fixed the issue that if PDP could not calculate some obligation in
response list then it dropped the remaining obligations
- moved common code to a separate method `calcValues()`
- added unit test for calcValues()

Return all successful obligations

---

Makefile
pep/client.go
pep/client_test.go
pep/mock_server_test.go
pep/streaming_client.go
pep/streaming_connection.go
pep/unary_client.go
pep/unary_client_test.go

All UTs and benchmarks (make build test bench) pass successfully.

Add timeouts to unary client

---

pdp/ast/jast/selector.go
pdp/ast/yast/selector.go
pdp/selector.go
pdp/selector/local/local.go
pdp/selector/local/local_test.go
pdp/selector/pip/pip.go
pdp/selector/pip/pip_test.go

this is a preparation step to further enhancements of selector expression

make selector interface more flexible
